name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod tidy

      - name: Verify build
        run: go build ./...

      - name: Vet code
        run: go vet ./...

      - name: Run all tests
        run: go test ./... -v

      - name: Run all tests with race detector
        run: go test ./... -v -race

  benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg:
          - ./collections/stack
          - ./collections/set
          - ./collections/queue
          - ./collections/concurrent/stack
          - ./collections/concurrent/set
          - ./collections/concurrent/queue
          - ./collections/concurrent/cmap
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod tidy

      - name: Run benchmarks for ${{ matrix.pkg }}
        run: go test ${{ matrix.pkg }} -bench=. -benchmem -run=^$
